export const SIGNIN_WITH_FACEBOOK_ATTEMPT = 'SIGNIN_WITH_FACEBOOK_ATTEMPT'
export const SIGNIN_WITH_FACEBOOK_SUCCESS = 'SIGNIN_WITH_FACEBOOK_SUCCESS'
export const SIGNIN_WITH_FACEBOOK_ERROR = 'SIGNIN_WITH_FACEBOOK_ERROR'

export const SIGNIN_WITH_GOOGLE_ATTEMPT = 'SIGNIN_WITH_GOOGLE_ATTEMPT'
export const SIGNIN_WITH_GOOGLE_SUCCESS = 'SIGNIN_WITH_GOOGLE_SUCCESS'
export const SIGNIN_WITH_GOOGLE_ERROR = 'SIGNIN_WITH_GOOGLE_ERROR'

export const LOGIN_WITH_EMAIL_ATTEMPT = 'LOGIN_WITH_EMAIL_ATTEMPT'
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS'
export const LOGIN_WITH_EMAIL_ERROR = 'LOGIN_WITH_EMAIL_ERROR'

export const SIGNUP_WITH_EMAIL_ATTEMPT = 'SIGNUP_WITH_EMAIL_ATTEMPT'
export const SIGNUP_WITH_EMAIL_SUCCESS = 'SIGNUP_WITH_EMAIL_SUCCESS'
export const SIGNUP_WITH_EMAIL_ERROR = 'SIGNUP_WITH_EMAIL_ERROR'
